export const NOTEBOOK_ASSIST_CONTEXT_WINDOW_SIZE = 5;
export const NOTEBOOK_PARSED_PREVIEW_LIMIT = 12;
export const NOTEBOOK_PARSED_PREVIEW_CHARS = 10000;
export const NOTEBOOK_CHUNKS_FETCH_LIMIT = 160;
export const NOTEBOOK_CHUNKS_PAGE_SIZE = 10;
